all:
  hosts:
    my_instance:
      ansible_user: root
      ansible_host: 188.166.187.180
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      code_server_password: qwerty
      code_server_domain: code-188.166.187.180.nip.io
      