- name: Update variables
  hosts: my_instance
  become: true
  tasks:
  - name: Update code server password
    replace: 
      path: /lib/systemd/system/code-server.service
      regexp: '__code_server_password__'
      replace: "{{ code_server_password }}"
  - name: Update code server password
    replace:
      path: /etc/nginx/sites-available/code-server.conf
      regexp: '__code_server_domain__'
      replace: "{{ code_server_domain }}"
  - name: Start and enable code-server.service
    systemd:
      name: code-server
      daemon_reload: true
      enabled: true
      state: restarted
  - name: Start and enable nginx
    systemd:
      name: nginx
      daemon_reload: true
      enabled: true
      state: restarted